// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ProxyHTTPRequest(arg1:main.ProxyRequest):Promise<main.ProxyResponse>;
